import 'reflect-metadata';
import {types} from '@typegoose/typegoose';
import {Container} from 'inversify';
import {Component} from './types/component.types.js';
import LoggerService from './common/logger/logger.service.js';
import {LoggerInterface} from './common/logger/logger.interface.js';
import ConfigService from './common/config/config.service.js';
import {ConfigInterface} from './common/config/config.interface.js';
import DatabaseService from './common/database-client/database.service.js';
import {DatabaseInterface} from './common/database-client/database.interface.js';
import UserService from './modules/user/user.service.js';
import {UserServiceInterface} from './modules/user/user-service.interface.js';
import {UserEntity, UserModel} from './modules/user/user.entity.js';
import FilmService from './modules/film/film.service.js';
import {FilmServiceInterface} from './modules/film/film-service.interface.js';
import {FilmEntity, FilmModel} from './modules/film/film.entity.js';
import CommentService from './modules/comment/comment.service.js';
import {CommentServiceInterface} from './modules/comment/comment-service.interface.js';
import {CommentEntity, CommentModel} from './modules/comment/comment.entity.js';
import FavoriteService from './modules/favorite/favorite.service.js';
import {FavoriteServiceInterface} from './modules/favorite/favorite-service.interface.js';
import {FavoriteEntity, FavoriteModel} from './modules/favorite/favorite.entity.js';
import {ControllerInterface} from './common/controller/controller.interface.js';
import FavoriteController from './modules/favorite/favorite.controller.js';
import UserController from './modules/user/user.controller.js';
import FilmController from './modules/film/film.controller.js';
import CommentController from './modules/comment/comment.controller.js';
import ExceptionFilter from './common/errors/exception-filter.js';
import {ExceptionFilterInterface} from './common/errors/exception-filter.interface.js';

import Application from './app/application.js';

const applicationContainer = new Container();
applicationContainer.bind<Application>(Component.Application).to(Application).inSingletonScope();
applicationContainer.bind<LoggerInterface>(Component.LoggerInterface).to(LoggerService).inSingletonScope();
applicationContainer.bind<ConfigInterface>(Component.ConfigInterface).to(ConfigService).inSingletonScope();
applicationContainer.bind<DatabaseInterface>(Component.DatabaseInterface).to(DatabaseService).inSingletonScope();
applicationContainer.bind<UserServiceInterface>(Component.UserServiceInterface).to(UserService);
applicationContainer.bind<types.ModelType<UserEntity>>(Component.UserModel).toConstantValue(UserModel);
applicationContainer.bind<FilmServiceInterface>(Component.FilmServiceInterface).to(FilmService);
applicationContainer.bind<types.ModelType<FilmEntity>>(Component.FilmModel).toConstantValue(FilmModel);
applicationContainer.bind<CommentServiceInterface>(Component.CommentServiceInterface).to(CommentService);
applicationContainer.bind<types.ModelType<CommentEntity>>(Component.CommentModel).toConstantValue(CommentModel);
applicationContainer.bind<FavoriteServiceInterface>(Component.FavoriteServiceInterface).to(FavoriteService);
applicationContainer.bind<types.ModelType<FavoriteEntity>>(Component.FavoriteModel).toConstantValue(FavoriteModel);

applicationContainer.bind<ControllerInterface>(Component.FavoriteController).to(FavoriteController).inSingletonScope();
applicationContainer.bind<ControllerInterface>(Component.UserController).to(UserController).inSingletonScope();
applicationContainer.bind<ControllerInterface>(Component.FilmController).to(FilmController).inSingletonScope();
applicationContainer.bind<ControllerInterface>(Component.CommentController).to(CommentController).inSingletonScope();
applicationContainer.bind<ExceptionFilterInterface>(Component.ExceptionFilterInterface).to(ExceptionFilter).inSingletonScope();

const application = applicationContainer.get<Application>(Component.Application);
await application.init();
